services:
  - type: worker
    name: discord-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: SUMMARY_CHANNEL_ID
        sync: false